apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-monitoring
  template:
    metadata:
      labels:
        app: devops-monitoring
    spec:
      containers:
        - name: devops-monitoring
          image: devops-monitoring:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
